### PR TITLE
update rust-nightly to 1.25

### PR DESCRIPTION
**Pull request by johalun**
Q&A still don't pass but it might be just a quick fix. This is as far as I will work on this. I could build everything and extract the toolchain from work/stage which is enough for me since I use rustup to handle toolchains.

### CODE REVIEW

**Comment by johalun** [comment]
I had to split the patch-sanitizer file because for some reason the Cargo.toml hunk makes the next hunk fail. I move that hunk to a separate file.

**Comment by valpackett** [comment]
ooh nice!! I've tried to upgrade it a couple weeks ago (changing `STDF` to more automatic name detection) but it failed to compile. Trying to build this now.

**Comment by valpackett** [comment]
```
/bin/rm -f /usr/ports/lang/rust-nightly/work/stage/usr/local/share/doc/rust/*.old                                                                         
rm: /usr/ports/lang/rust-nightly/work/stage/usr/local/share/doc/rust/html.old: is a directory
```

hmm, maybe this is just because of re-running make without cleaning, but I had to delete that manually

**Comment by valpackett** [comment]
Merged, thanks.

(Silly GitHub, didn't detect `git am` even though it offers a link to the PR as a patch…)

**Pull request closed without merging**
